### ISSUE TITLE
Enunciado actividad  5.1

### ISSUE THREAD

**Issue by cuococarlos** [gobstones/curso-lpysd2#1]
Sugeriría agregar en la descripción ,que es necesario tildar todas las manzanas para el correcto funcionamiento del programa.
Para evitar casos como el siguente:
![actividad 5 1](https://user-images.githubusercontent.com/5522872/46572215-44994300-c958-11e8-8f8d-d3f2caab7402.png)

**Comment by fidel-ml** [comment]
Hecho. Fijate y si hay algo más para decir, reabrí. :D
