### ISSUE TITLE
Agregar operación primitiva "es"

### ISSUE THREAD

**Issue by asanzo** [gobstones/curso-lpysd2#4]
Plantea @churrocode (Juli) algo interesante que le pasó en el aula de secundaria con sus alumnos: es difícil que se den cuenta que mediante el `==` (el igual),  yo puedo saber si _algo es el dato X_.

Por ejemplo, acá, en "El rey, el caballo...":

![Selección_999(155)](https://user-images.githubusercontent.com/5421992/54619364-35f4a300-4a43-11e9-8f12-411ac6205df8.png)

Estaría bueno que hubiera la operación "ES":

![Selección_999(155)](https://user-images.githubusercontent.com/5421992/54619469-6a685f00-4a43-11e9-8dbf-a356a236b580.png)

Para mí podría agregarse en el mismo dropdown del `==`, ó reemplazar el `==` por `es`.

**Comment by fidel-ml** [comment]
Hecho para "El rey, el caballo..."
