### ISSUE TITLE
Cambiar "Decir numero" por "Decir este número"

### ISSUE THREAD

**Issue by asanzo** [gobstones/curso-lpysd2#5]
Esto haría que este error se entienda mejor:

![Selección_999(156)](https://user-images.githubusercontent.com/5421992/54645318-555af280-4a7a-11e9-9bde-3e8c862f285f.png)

Este error se produce porque parece que a esa primitiva le podés pasar una carta.

Opiniones?

**Comment by fidel-ml** [comment]
Listo (al menos en un par de actividades. Hay que revisar al unificar el extra en forma común)
