### ISSUE TITLE
Descubrir la carta: Invertir el orden en el toolbox

### ISSUE THREAD

**Issue by asanzo** [gobstones/curso-lpysd2#6]
![Selección_999(157)](https://user-images.githubusercontent.com/5421992/54645370-8fc48f80-4a7a-11e9-8194-5ee20954219d.png)

Esto permitirá que se minimice la ocurrencia de este error:

![Selección_999(158)](https://user-images.githubusercontent.com/5421992/54645431-c26e8800-4a7a-11e9-8e44-d0a7b3784953.png)

que ocurre porque la gente agarra del toolbox en orden.

**Comment by fidel-ml** [comment]
Resuelto.
